
package proxy.proxyUser;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "User", targetNamespace = "http://Controllers.cooolab.management.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface User {


    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "SaveUser")
    @RequestWrapper(localName = "SaveUser", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyUser.SaveDemandeConge")
    @ResponseWrapper(localName = "SaveUserResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyUser.SaveDemandeCongeResponse")
    @Action(input = "http://Controllers.cooolab.management.com/User/SaveUserRequest", output = "http://Controllers.cooolab.management.com/User/SaveUserResponse")
    public void saveUser(
        @WebParam(name = "arg0", targetNamespace = "")
        Object[] arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyUser.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyUser.AddUserResponse")
    @Action(input = "http://Controllers.cooolab.management.com/User/addUserRequest", output = "http://Controllers.cooolab.management.com/User/addUserResponse")
    public List<Object> addUser();

    /**
     * 
     * @return
     *     returns java.util.List<proxy.proxyUser.User_Type>
     */
    @WebMethod(operationName = "ListUsers")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListUsers", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyUser.ListUsers")
    @ResponseWrapper(localName = "ListUsersResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyUser.ListUsersResponse")
    @Action(input = "http://Controllers.cooolab.management.com/User/ListUsersRequest", output = "http://Controllers.cooolab.management.com/User/ListUsersResponse")
    public List<User_Type> listUsers();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod(operationName = "EditUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "EditUser", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyUser.EditUser")
    @ResponseWrapper(localName = "EditUserResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyUser.EditUserResponse")
    @Action(input = "http://Controllers.cooolab.management.com/User/EditUserRequest", output = "http://Controllers.cooolab.management.com/User/EditUserResponse")
    public List<Object> editUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "DeleteUser")
    @RequestWrapper(localName = "DeleteUser", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyUser.DeleteUser")
    @ResponseWrapper(localName = "DeleteUserResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyUser.DeleteUserResponse")
    @Action(input = "http://Controllers.cooolab.management.com/User/DeleteUserRequest", output = "http://Controllers.cooolab.management.com/User/DeleteUserResponse")
    public void deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod(operationName = "UpdateUser")
    @RequestWrapper(localName = "UpdateUser", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyUser.UpdateUser")
    @ResponseWrapper(localName = "UpdateUserResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyUser.UpdateUserResponse")
    @Action(input = "http://Controllers.cooolab.management.com/User/UpdateUserRequest", output = "http://Controllers.cooolab.management.com/User/UpdateUserResponse")
    public void updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User_Type arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod(operationName = "ShowUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ShowUser", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyUser.ShowUser")
    @ResponseWrapper(localName = "ShowUserResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyUser.ShowUserResponse")
    @Action(input = "http://Controllers.cooolab.management.com/User/ShowUserRequest", output = "http://Controllers.cooolab.management.com/User/ShowUserResponse")
    public List<Object> showUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
