
package proxy.proxyUser;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "UserControllerService", targetNamespace = "http://Controllers.cooolab.management.com/", wsdlLocation = "http://127.0.0.1:8091/user?wsdl")
public class UserControllerService
    extends Service
{

    private static final URL USERCONTROLLERSERVICE_WSDL_LOCATION;
    private static final WebServiceException USERCONTROLLERSERVICE_EXCEPTION;
    private static final QName USERCONTROLLERSERVICE_QNAME = new QName("http://Controllers.cooolab.management.com/", "UserControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8091/user?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERCONTROLLERSERVICE_WSDL_LOCATION = url;
        USERCONTROLLERSERVICE_EXCEPTION = e;
    }

    public UserControllerService() {
        super(__getWsdlLocation(), USERCONTROLLERSERVICE_QNAME);
    }

    public UserControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERCONTROLLERSERVICE_QNAME, features);
    }

    public UserControllerService(URL wsdlLocation) {
        super(wsdlLocation, USERCONTROLLERSERVICE_QNAME);
    }

    public UserControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERCONTROLLERSERVICE_QNAME, features);
    }

    public UserControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns User
     */
    @WebEndpoint(name = "UserPort")
    public User getUserPort() {
        return super.getPort(new QName("http://Controllers.cooolab.management.com/", "UserPort"), User.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns User
     */
    @WebEndpoint(name = "UserPort")
    public User getUserPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Controllers.cooolab.management.com/", "UserPort"), User.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERCONTROLLERSERVICE_EXCEPTION!= null) {
            throw USERCONTROLLERSERVICE_EXCEPTION;
        }
        return USERCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
