
package proxy.proxyDepartment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "DepartmentControllerService", targetNamespace = "http://Controllers.cooolab.management.com/", wsdlLocation = "http://127.0.0.1:8091/department?wsdl")
public class DepartmentControllerService
    extends Service
{

    private static final URL DEPARTMENTCONTROLLERSERVICE_WSDL_LOCATION;
    private static final WebServiceException DEPARTMENTCONTROLLERSERVICE_EXCEPTION;
    private static final QName DEPARTMENTCONTROLLERSERVICE_QNAME = new QName("http://Controllers.cooolab.management.com/", "DepartmentControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8091/department?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEPARTMENTCONTROLLERSERVICE_WSDL_LOCATION = url;
        DEPARTMENTCONTROLLERSERVICE_EXCEPTION = e;
    }

    public DepartmentControllerService() {
        super(__getWsdlLocation(), DEPARTMENTCONTROLLERSERVICE_QNAME);
    }

    public DepartmentControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEPARTMENTCONTROLLERSERVICE_QNAME, features);
    }

    public DepartmentControllerService(URL wsdlLocation) {
        super(wsdlLocation, DEPARTMENTCONTROLLERSERVICE_QNAME);
    }

    public DepartmentControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEPARTMENTCONTROLLERSERVICE_QNAME, features);
    }

    public DepartmentControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DepartmentControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Department
     */
    @WebEndpoint(name = "DepartmentPort")
    public Department getDepartmentPort() {
        return super.getPort(new QName("http://Controllers.cooolab.management.com/", "DepartmentPort"), Department.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Department
     */
    @WebEndpoint(name = "DepartmentPort")
    public Department getDepartmentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Controllers.cooolab.management.com/", "DepartmentPort"), Department.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEPARTMENTCONTROLLERSERVICE_EXCEPTION!= null) {
            throw DEPARTMENTCONTROLLERSERVICE_EXCEPTION;
        }
        return DEPARTMENTCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
