
package proxy.proxyDepartment;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Department", targetNamespace = "http://Controllers.cooolab.management.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Department {


    /**
     * 
     * @return
     *     returns proxy.proxyDepartment.Departement
     */
    @WebMethod(operationName = "AddDepartment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AddDepartment", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDepartment.AddDepartment")
    @ResponseWrapper(localName = "AddDepartmentResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDepartment.AddDepartmentResponse")
    @Action(input = "http://Controllers.cooolab.management.com/Department/AddDepartmentRequest", output = "http://Controllers.cooolab.management.com/Department/AddDepartmentResponse")
    public Departement addDepartment();

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod(operationName = "DeleteDepartment")
    @RequestWrapper(localName = "DeleteDepartment", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDepartment.DeleteDepartment")
    @ResponseWrapper(localName = "DeleteDepartmentResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDepartment.DeleteDepartmentResponse")
    @Action(input = "http://Controllers.cooolab.management.com/Department/DeleteDepartmentRequest", output = "http://Controllers.cooolab.management.com/Department/DeleteDepartmentResponse")
    public void deleteDepartment(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.proxyDepartment.Departement>
     */
    @WebMethod(operationName = "ListDepartments")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListDepartments", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDepartment.ListDepartments")
    @ResponseWrapper(localName = "ListDepartmentsResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDepartment.ListDepartmentsResponse")
    @Action(input = "http://Controllers.cooolab.management.com/Department/ListDepartmentsRequest", output = "http://Controllers.cooolab.management.com/Department/ListDepartmentsResponse")
    public List<Departement> listDepartments();

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "SaveDepartment")
    @RequestWrapper(localName = "SaveDepartment", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDepartment.SaveDemandeConge")
    @ResponseWrapper(localName = "SaveDepartmentResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDepartment.SaveDemandeCongeResponse")
    @Action(input = "http://Controllers.cooolab.management.com/Department/SaveDepartmentRequest", output = "http://Controllers.cooolab.management.com/Department/SaveDepartmentResponse")
    public void saveDepartment(
        @WebParam(name = "arg0", targetNamespace = "")
        Departement arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.proxyDepartment.Departement
     */
    @WebMethod(operationName = "EditDepartment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "EditDepartment", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDepartment.EditDepartment")
    @ResponseWrapper(localName = "EditDepartmentResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDepartment.EditDepartmentResponse")
    @Action(input = "http://Controllers.cooolab.management.com/Department/EditDepartmentRequest", output = "http://Controllers.cooolab.management.com/Department/EditDepartmentResponse")
    public Departement editDepartment(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "UpdateDepartment")
    @RequestWrapper(localName = "UpdateDepartment", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDepartment.UpdateDepartment")
    @ResponseWrapper(localName = "UpdateDepartmentResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDepartment.UpdateDepartmentResponse")
    @Action(input = "http://Controllers.cooolab.management.com/Department/UpdateDepartmentRequest", output = "http://Controllers.cooolab.management.com/Department/UpdateDepartmentResponse")
    public void updateDepartment(
        @WebParam(name = "arg0", targetNamespace = "")
        Departement arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showDepartment", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDepartment.ShowDepartment")
    @ResponseWrapper(localName = "showDepartmentResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDepartment.ShowDepartmentResponse")
    @Action(input = "http://Controllers.cooolab.management.com/Department/showDepartmentRequest", output = "http://Controllers.cooolab.management.com/Department/showDepartmentResponse")
    public List<Object> showDepartment(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
