
package proxy.proxyProfile;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Profile", targetNamespace = "http://Controllers.cooolab.management.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Profile {


    /**
     * 
     * @return
     *     returns proxy.proxyProfile.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editProfile", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyProfile.EditProfile")
    @ResponseWrapper(localName = "editProfileResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyProfile.EditProfileResponse")
    @Action(input = "http://Controllers.cooolab.management.com/Profile/editProfileRequest", output = "http://Controllers.cooolab.management.com/Profile/editProfileResponse")
    public User editProfile();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateProfile", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyProfile.UpdateProfile")
    @ResponseWrapper(localName = "updateProfileResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyProfile.UpdateProfileResponse")
    @Action(input = "http://Controllers.cooolab.management.com/Profile/updateProfileRequest", output = "http://Controllers.cooolab.management.com/Profile/updateProfileResponse")
    public void updateProfile(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

}
