
package proxy.proxyProfile;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ProfileControllerService", targetNamespace = "http://Controllers.cooolab.management.com/", wsdlLocation = "http://127.0.0.1:8091/profile?wsdl")
public class ProfileControllerService
    extends Service
{

    private static final URL PROFILECONTROLLERSERVICE_WSDL_LOCATION;
    private static final WebServiceException PROFILECONTROLLERSERVICE_EXCEPTION;
    private static final QName PROFILECONTROLLERSERVICE_QNAME = new QName("http://Controllers.cooolab.management.com/", "ProfileControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8091/profile?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROFILECONTROLLERSERVICE_WSDL_LOCATION = url;
        PROFILECONTROLLERSERVICE_EXCEPTION = e;
    }

    public ProfileControllerService() {
        super(__getWsdlLocation(), PROFILECONTROLLERSERVICE_QNAME);
    }

    public ProfileControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROFILECONTROLLERSERVICE_QNAME, features);
    }

    public ProfileControllerService(URL wsdlLocation) {
        super(wsdlLocation, PROFILECONTROLLERSERVICE_QNAME);
    }

    public ProfileControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROFILECONTROLLERSERVICE_QNAME, features);
    }

    public ProfileControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProfileControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Profile
     */
    @WebEndpoint(name = "ProfilePort")
    public Profile getProfilePort() {
        return super.getPort(new QName("http://Controllers.cooolab.management.com/", "ProfilePort"), Profile.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Profile
     */
    @WebEndpoint(name = "ProfilePort")
    public Profile getProfilePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Controllers.cooolab.management.com/", "ProfilePort"), Profile.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROFILECONTROLLERSERVICE_EXCEPTION!= null) {
            throw PROFILECONTROLLERSERVICE_EXCEPTION;
        }
        return PROFILECONTROLLERSERVICE_WSDL_LOCATION;
    }

}
