
package proxy.proxyDemandeConge;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "DemandeConge", targetNamespace = "http://Controllers.cooolab.management.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemandeConge {


    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "SaveDemandeConge")
    @RequestWrapper(localName = "SaveDemandeConge", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.SaveDemandeConge")
    @ResponseWrapper(localName = "SaveDemandeCongeResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.SaveDemandeCongeResponse")
    @Action(input = "http://Controllers.cooolab.management.com/DemandeConge/SaveDemandeCongeRequest", output = "http://Controllers.cooolab.management.com/DemandeConge/SaveDemandeCongeResponse")
    public void saveDemandeConge(
        @WebParam(name = "arg0", targetNamespace = "")
        DemandeConge_Type arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @RequestWrapper(localName = "updateLeaveRequestStatus", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.UpdateLeaveRequestStatus")
    @ResponseWrapper(localName = "updateLeaveRequestStatusResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.UpdateLeaveRequestStatusResponse")
    @Action(input = "http://Controllers.cooolab.management.com/DemandeConge/updateLeaveRequestStatusRequest", output = "http://Controllers.cooolab.management.com/DemandeConge/updateLeaveRequestStatusResponse")
    public void updateLeaveRequestStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.proxyDemandeConge.DemandeConge_Type>
     */
    @WebMethod(operationName = "ListMesDemandesConges")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListMesDemandesConges", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.ListMesDemandesConges")
    @ResponseWrapper(localName = "ListMesDemandesCongesResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.ListMesDemandesCongesResponse")
    @Action(input = "http://Controllers.cooolab.management.com/DemandeConge/ListMesDemandesCongesRequest", output = "http://Controllers.cooolab.management.com/DemandeConge/ListMesDemandesCongesResponse")
    public List<DemandeConge_Type> listMesDemandesConges();

    /**
     * 
     * @return
     *     returns java.util.List<proxy.proxyDemandeConge.DemandeConge_Type>
     */
    @WebMethod(operationName = "ListDepartementConges")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListDepartementConges", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.ListDepartementConges")
    @ResponseWrapper(localName = "ListDepartementCongesResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.ListDepartementCongesResponse")
    @Action(input = "http://Controllers.cooolab.management.com/DemandeConge/ListDepartementCongesRequest", output = "http://Controllers.cooolab.management.com/DemandeConge/ListDepartementCongesResponse")
    public List<DemandeConge_Type> listDepartementConges();

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "UpdateDemandeConge")
    @RequestWrapper(localName = "UpdateDemandeConge", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.UpdateDemandeConge")
    @ResponseWrapper(localName = "UpdateDemandeCongeResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.UpdateDemandeCongeResponse")
    @Action(input = "http://Controllers.cooolab.management.com/DemandeConge/UpdateDemandeCongeRequest", output = "http://Controllers.cooolab.management.com/DemandeConge/UpdateDemandeCongeResponse")
    public void updateDemandeConge(
        @WebParam(name = "arg0", targetNamespace = "")
        DemandeConge_Type arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.util.List<proxy.proxyDemandeConge.DemandeConge_Type>
     */
    @WebMethod(operationName = "ListDemandesConges")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListDemandesConges", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.ListDemandesConges")
    @ResponseWrapper(localName = "ListDemandesCongesResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.ListDemandesCongesResponse")
    @Action(input = "http://Controllers.cooolab.management.com/DemandeConge/ListDemandesCongesRequest", output = "http://Controllers.cooolab.management.com/DemandeConge/ListDemandesCongesResponse")
    public List<DemandeConge_Type> listDemandesConges(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1);

    /**
     * 
     * @return
     *     returns proxy.proxyDemandeConge.DemandeConge_Type
     */
    @WebMethod(operationName = "AddDemandeConge")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AddDemandeConge", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.AddDemandeConge")
    @ResponseWrapper(localName = "AddDemandeCongeResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.AddDemandeCongeResponse")
    @Action(input = "http://Controllers.cooolab.management.com/DemandeConge/AddDemandeCongeRequest", output = "http://Controllers.cooolab.management.com/DemandeConge/AddDemandeCongeResponse")
    public DemandeConge_Type addDemandeConge();

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.proxyDemandeConge.DemandeConge_Type
     */
    @WebMethod(operationName = "EditDemandeConge")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "EditDemandeConge", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.EditDemandeConge")
    @ResponseWrapper(localName = "EditDemandeCongeResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.EditDemandeCongeResponse")
    @Action(input = "http://Controllers.cooolab.management.com/DemandeConge/EditDemandeCongeRequest", output = "http://Controllers.cooolab.management.com/DemandeConge/EditDemandeCongeResponse")
    public DemandeConge_Type editDemandeConge(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "DeleteDemandeConge")
    @RequestWrapper(localName = "DeleteDemandeConge", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.DeleteDemandeConge")
    @ResponseWrapper(localName = "DeleteDemandeCongeResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxy.proxyDemandeConge.DeleteDemandeCongeResponse")
    @Action(input = "http://Controllers.cooolab.management.com/DemandeConge/DeleteDemandeCongeRequest", output = "http://Controllers.cooolab.management.com/DemandeConge/DeleteDemandeCongeResponse")
    public void deleteDemandeConge(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
