
package proxy.proxyLogin;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Login", targetNamespace = "http://Controllers.cooolab.management.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Login {


    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns proxyLogin.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loginUser", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxyLogin.LoginUser")
    @ResponseWrapper(localName = "loginUserResponse", targetNamespace = "http://Controllers.cooolab.management.com/", className = "proxyLogin.LoginUserResponse")
    @Action(input = "http://Controllers.cooolab.management.com/Login/loginUserRequest", output = "http://Controllers.cooolab.management.com/Login/loginUserResponse")
    public User loginUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
