
package proxy.proxyLogin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "LoginControllerService", targetNamespace = "http://Controllers.cooolab.management.com/", wsdlLocation = "http://127.0.0.1:8091/login?wsdl")
public class LoginControllerService
    extends Service
{

    private static final URL LOGINCONTROLLERSERVICE_WSDL_LOCATION;
    private static final WebServiceException LOGINCONTROLLERSERVICE_EXCEPTION;
    private static final QName LOGINCONTROLLERSERVICE_QNAME = new QName("http://Controllers.cooolab.management.com/", "LoginControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8091/login?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGINCONTROLLERSERVICE_WSDL_LOCATION = url;
        LOGINCONTROLLERSERVICE_EXCEPTION = e;
    }

    public LoginControllerService() {
        super(__getWsdlLocation(), LOGINCONTROLLERSERVICE_QNAME);
    }

    public LoginControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGINCONTROLLERSERVICE_QNAME, features);
    }

    public LoginControllerService(URL wsdlLocation) {
        super(wsdlLocation, LOGINCONTROLLERSERVICE_QNAME);
    }

    public LoginControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGINCONTROLLERSERVICE_QNAME, features);
    }

    public LoginControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Login
     */
    @WebEndpoint(name = "LoginPort")
    public Login getLoginPort() {
        return super.getPort(new QName("http://Controllers.cooolab.management.com/", "LoginPort"), Login.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Login
     */
    @WebEndpoint(name = "LoginPort")
    public Login getLoginPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Controllers.cooolab.management.com/", "LoginPort"), Login.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGINCONTROLLERSERVICE_EXCEPTION!= null) {
            throw LOGINCONTROLLERSERVICE_EXCEPTION;
        }
        return LOGINCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
